#NumPy

고성능 수치 계산(배열)을 위한 파이썬 라이브러리

In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [3]:
temp = np.array([1, 2, 3])
print(type(temp))

<class 'numpy.ndarray'>


> 추가적인 공부 : Quick Tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [4]:
data1 = [1, 2, 3]
data1

[1, 2, 3]

In [5]:
data2 = [1, 1, 2, 2, 3, 4]
data2

[1, 1, 2, 2, 3, 4]

In [6]:
my_array1 = np.array(data1)
print(my_array1)
print(my_array1.shape)

[1 2 3]
(3,)


In [8]:
my_array2 = np.array(data2)
print(my_array2)
print(my_array2.shape)

[1 1 2 2 3 4]
(6,)


In [9]:
my_array3 = np.array([3, 6, 9, 12])
print(my_array3.dtype)

int64


- NumPy는 자료형이 다르면 오류가 발생할 수 있으므로 항상 데이터 타입을 확인하는 습관을 들이자
- Data types 더보기 : https://numpy.org/devdocs/user/basics.types.html

In [10]:
my_array4 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18], [20, 22, 24]])
my_array4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [11]:
my_array4.shape

(4, 3)

In [12]:
my_array5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
my_array5.shape

(2, 2, 2)

In [13]:
arange_array = np.arange(5)
arange_array

array([0, 1, 2, 3, 4])

In [15]:
arange_array2 = np.arange(1, 9, 3)
arange_array2

array([1, 4, 7])

In [16]:
zeros_array = np.zeros((3, 2))
print(zeros_array)
print("Data type is : ", zeros_array.dtype)
print("Data Shape is : ", zeros_array.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
Data type is :  float64
Data Shape is :  (3, 2)


In [17]:
ones_array = np.ones((3, 4), dtype = 'int32')
print(ones_array)
print("Data type is : ", ones_array.dtype)
print("Data Shape is : ", ones_array.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Data type is :  int32
Data Shape is :  (3, 4)


In [18]:
after_reshape = ones_array.reshape(6, 2)
print(after_reshape)
print("Data Shape is : ", after_reshape.shape)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Data Shape is :  (6, 2)


In [20]:
after_reshape2 = ones_array.reshape(2, 3, 2)
print(after_reshape2)
print("Data Shape is : ", after_reshape2.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
Data Shape is :  (2, 3, 2)


In [21]:
after_reshape3 = ones_array.reshape(-1, 6)
print('reshape(-1, 6)?\n')
print(after_reshape3)

reshape(-1, 6)?

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [22]:
 after_reshape4 = ones_array.reshape(4, -1)
 print('reshape(4, -1)?\n')
 print(after_reshape4)

reshape(4, -1)?

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
